
import type { NavItem, ServiceMenuItem, Product, TimelineEvent, BlogPost, BlogCategory, ProductSubMenuItem, TechStackItem, Testimonial, FeaturedVideo, OpenPosition, YouTubeShort } from '@/types';
import {
  Code, Smartphone, Brain, Cloud, Palette, Users, Bot, HomeIcon, Layers, Building2, FileText, FileCode,
  Lightbulb, MessageCircle, ShieldCheck, PenTool, Server, Cpu, Gem, GitBranch, DatabaseZap, BarChartBig,
  Info, Briefcase, Mail, Globe, GitMerge, LayoutGrid, Puzzle, TrendingUp, Settings, DollarSign, Star, Link as LinkIcon,
  Clock, Car, QrCode, Package, Home, School, ChefHat, MessageSquare as MessageSquareIcon, Wrench, Truck, MonitorSmartphone, BarChart3, CircleDollarSign, Users2, Award, Handshake, CalendarPlus,
  DownloadCloud, Newspaper, CalendarClock, HelpCircle, BookOpenText, MailPlus, BarChartHorizontalBig, PlayCircle, Container, Share, Database, Settings2, Network, ServerCog, Shield, AppWindow, CodeXml, Cable, FileJson, TerminalSquare, Github, Linkedin, Twitter, Facebook, Send, Instagram, Film
} from 'lucide-react';

export const SITE_NAME = "Cubic Dot";

export const NAV_LINKS: NavItem[] = [
  { href: "/", label: "Home", icon: Home },
  { href: "/ai", label: "AI", icon: Bot },
  { href: "/services", label: "Services", icon: Layers },
  { href: "/products", label: "Products", icon: Smartphone },
  { href: "/company", label: "Company", icon: Building2 },
  { href: "/blog", label: "Resources", icon: FileText },
];

export const COMPANY_SUB_LINKS: NavItem[] = [
  {
    href: "/company",
    label: "Our Story",
    icon: Info,
    description: "Explore our purpose, aspirations, core beliefs, founding narrative, leadership, and company evolution."
  },
  {
    href: "/pricing",
    label: "Pricing",
    icon: CircleDollarSign,
    description: "Transparent pricing frameworks available for individuals, nascent businesses, and established corporations."
  },
  {
    href: "/consultancy",
    label: "Consultancy",
    icon: Briefcase,
    description: "Offering expert consulting services, including talent acquisition guidance."
  },
  {
    href: "/contact",
    label: "Contact Us",
    icon: Mail,
    description: "Methods to reach us: contact form, phone, email, office locations, interactive map integration, and social media channels."
  },
  {
    href: "/career",
    label: "Career",
    icon: Briefcase,
    description: "Current job openings, work culture, benefits, hiring process, and intern programs."
  },
  {
    href: "#",
    label: "Our Team",
    icon: Users2,
    description: "Photos, bios, and roles of key team members (adds a human touch)."
  },
  {
    href: "#",
    label: "Why Choose Us",
    icon: Star,
    description: "Key differentiators, client success stories, testimonials, and USPs."
  },
  {
    href: "#",
    label: "Partners & Affiliations",
    icon: Handshake,
    description: "Tech alliances, certifications, and strategic partners."
  },
];

export const PRODUCT_SUB_LINKS: ProductSubMenuItem[] = [
  {
    label: "Trackzy",
    subtitle: "(CCL Time Tracker)",
    description: "Smart time tracking for productive teams.",
    href: "#",
    icon: Clock,
  },
  {
    label: "AutoCleanse",
    subtitle: "(Doorstep Car Cleaning Service)",
    description: "Doorstep car wash, zero hassle.",
    href: "#",
    icon: Car,
  },
  {
    label: "QConnect",
    subtitle: "(Scan & Connect)",
    description: "Scan the QR. Connect instantly.",
    href: "#",
    icon: QrCode,
  },
  {
    label: "SwiftDrop",
    subtitle: "(Parcel Delivery #1)",
    description: "Next-gen parcel delivery at your command.",
    href: "#",
    icon: Package,
  },
  {
    label: "Neighbory",
    subtitle: "(Society Management)",
    description: "Simplifying society and community living.",
    href: "#",
    icon: HomeIcon,
  },
  {
    label: "ClientNest",
    subtitle: "(CRM)",
    description: "CRM that grows with your business.",
    href: "#",
    icon: Briefcase,
  },
  {
    label: "EduFlow",
    subtitle: "(School Management)",
    description: "Everything your school needs, in one place.",
    href: "#",
    icon: School,
  },
  {
    label: "DineOS",
    subtitle: "(Restra)",
    description: "Modern software for modern restaurants.",
    href: "#",
    icon: ChefHat,
  },
  {
    label: "WizZap",
    subtitle: "(WhatsApp Automation)",
    description: "Automated WhatsApp messaging for smart outreach.",
    href: "#",
    icon: MessageSquareIcon,
  },
  {
    label: "TeamSage",
    subtitle: "(HRMS)",
    description: "Smart HRMS for growing teams.",
    href: "#",
    icon: Users,
  },
  {
    label: "Servion",
    subtitle: "(On-demand Service App)",
    description: "On-demand services, reimagined.",
    href: "#",
    icon: Wrench,
  },
  {
    label: "DropChain",
    subtitle: "(Parcel Delivery #2)",
    description: "Reliable parcel logistics powered by smart tech.",
    href: "#",
    icon: Package,
  },
  {
    label: "Fleetzy",
    subtitle: "(Fleet Management)",
    description: "Fleet tracking and logistics, simplified.",
    href: "#",
    icon: Truck,
  },
  {
    label: "InstaSite",
    subtitle: "(Miniweb)",
    description: "Launch stunning mini websites in minutes.",
    href: "#",
    icon: MonitorSmartphone,
  },
  {
    label: "XpressRoute",
    subtitle: "(Parcel Delivery #3)",
    description: "Speed up your delivery, the smart way.",
    href: "#",
    icon: Package,
  },
  {
    label: "Pulselytics",
    subtitle: "(Social Media Data Dashboard)",
    description: "Real-time analytics for your social presence.",
    href: "#",
    icon: BarChart3,
  },
];

export const RESOURCES_SUB_LINKS: NavItem[] = [
  {
    href: "/blog",
    label: "Blog",
    icon: FileText,
    description: "Articles on tech trends, case studies, coding tips, AI advancements, and startup advice.",
  },
  {
    href: "#",
    label: "Case Studies",
    icon: BarChartHorizontalBig,
    description: "Real client success stories with challenges, solutions, results, and testimonials.",
  },
  {
    href: "#",
    label: "Whitepapers & Reports",
    icon: DownloadCloud,
    description: "Downloadable PDFs on industry insights, AI, blockchain, or software strategy.",
  },
  {
    href: "#",
    label: "News & Announcements",
    icon: Newspaper,
    description: "Product launches, event participation, partnerships, awards, or media mentions.",
  },
  {
    href: "#",
    label: "Webinars & Events",
    icon: CalendarClock,
    description: "Upcoming webinars, past recordings, tech meetups, or training events.",
  },
  {
    href: "#",
    label: "Help Center / FAQs",
    icon: HelpCircle,
    description: "Support articles, onboarding guides, and general help topics.",
  },
  {
    href: "#",
    label: "Tutorials & How-Tos",
    icon: BookOpenText,
    description: "Technical tutorials, integrations, and walkthroughs for developers and clients.",
  },
  {
    href: "#",
    label: "Newsletter Signup",
    icon: MailPlus,
    description: "A place to collect emails for a monthly newsletter on company updates and tech trends.",
  },
];


export const SERVICES_DATA: ServiceMenuItem[] = [
  {
    title: "Concept & Design",
    slug: "ideation-design",
    icon: Lightbulb,
    subServices: [
      { title: "User Interface & Experience Design", slug: "ui-ux-design", description: "Wireframes, prototypes, high-fidelity designs, and usability testing." },
      { title: "Product Strategy & Planning", slug: "product-roadmap", description: "Strategic development of minimum viable products, growth plans, feature ranking, and project schedules." },
      { title: "Design Thinking Sessions", slug: "design-thinking-workshops", description: "Collaborative workshops aimed at uncovering user challenges and sparking creative solutions." },
      { title: "User Insights & Personas", slug: "user-research-personas", description: "Analyzing target demographics, conducting interviews, developing detailed user profiles, and mapping user behavior." },
      { title: "Digital Branding", slug: "brand-identity-design", description: "Crafting unique logos, defining color palettes, selecting fonts, and establishing brand standards for online visibility." },
      { title: "Content Structuring", slug: "information-architecture", description: "Developing website maps, organizing navigation flows, and defining the logical arrangement of information." },
      { title: "Interactive Prototyping", slug: "prototyping-wireframing", description: "Creating functional mockups and basic screen layouts to rapidly test and refine concepts." },
      { title: "Market & Rival Analysis", slug: "competitor-analysis", description: "Investigating the market landscape and comparing user experience/interface elements to establish a competitive edge." },
    ],
    description: "Transforming concepts into engaging and user-centric digital experiences.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "design thinking",
  },
  {
    title: "Mobile Solutions Creation",
    slug: "mobile-app-development",
    icon: Smartphone,
    subServices: [
      { title: "Develop Android Applications", slug: "android-app-development", description: "Crafting native applications for Android devices utilizing Java or Kotlin to ensure high performance and adaptability." },
      { title: "Develop iOS Applications", slug: "ios-app-development", description: "Developing native applications for iPhones and iPads using Swift, tailored for the Apple ecosystem." },
      { title: "Develop Cross-Platform Apps", slug: "cross-platform-app-development", description: "Building mobile applications compatible with both iOS and Android operating systems using frameworks like React Native or Flutter." },
      { title: "Develop Progressive Web Apps (PWA)", slug: "progressive-web-apps", description: "Creating web applications that offer a user experience similar to native apps when accessed via mobile browsers." },
      { title: "Mobile Interface Design", slug: "mobile-app-ui-ux-design-sub", description: "Designing bespoke user interfaces and strategizing for mobile-specific user experiences." },
      { title: "Application Testing & Quality Assurance", slug: "mobile-app-testing-qa", description: "Conducting tests for functionality, performance, and user interaction to guarantee flawless application launches." },
      { title: "Application Deployment & Release", slug: "mobile-app-deployment-launch", description: "Facilitating the publication of applications to the Google Play Store and Apple App Store, ensuring all compliance requirements are met." },
      { title: "Application Support & Upkeep", slug: "mobile-app-maintenance-support-sub", description: "Providing continuous updates, monitoring, troubleshooting, and enhancements for features after the application launch." },
    ],
    description: "Building high-performance, scalable mobile applications for iOS and Android.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "mobile development",
  },
  {
    title: "Web Solutions",
    slug: "web-development",
    icon: Globe,
    subServices: [
      { title: "Website Building", slug: "website-development", description: "Responsive business websites, portfolios, landing pages, and CMS sites." },
      { title: "Develop Web Applications", slug: "web-app-development-sub", description: "Developing bespoke web applications for purposes such as internal systems, SaaS platforms, dashboards, and user portals." },
      { title: "E-commerce Solutions", slug: "e-commerce-development", description: "Establishing online retail platforms using systems like WooCommerce, Shopify, or unique, purpose-built solutions." },
      { title: "Frontend Development", slug: "frontend-development", description: "Creating user-facing interfaces with contemporary JavaScript frameworks including React, Next.js, and Vue.js." },
      { title: "Backend Development", slug: "backend-development", description: "Building the server-side logic and robust APIs using technologies such as Node.js, Laravel, and Python/Django." },
      { title: "CMS & Administration Panel Building", slug: "cms-custom-admin-panels", description: "Setting up and customizing content management systems like WordPress, Strapi, Headless CMSs, or constructing entirely custom admin interfaces." },
      { title: "API Services", slug: "web-api-integration-development-sub", description: "Providing services for creating and integrating APIs, including RESTful APIs, GraphQL, and connections with external third-party services." },
      { title: "Speed & Efficiency Improvement", slug: "web-performance-optimization", description: "Enhancing website loading times, search engine optimization, accessibility for users, and performance metrics like Core Web Vitals." },
      { title: "Web Hosting & Release", slug: "web-hosting-deployment", description: "Configuring adaptable hosting environments on providers such as AWS, Vercel, Netlify, and DigitalOcean." },
    ],
    description: "Crafting dynamic websites and powerful web applications tailored to your needs.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "web design",
  },
  {
    title: "Custom Software Building",
    slug: "software-development",
    icon: Server,
    subServices: [
      { title: "Tailored Software Creation", slug: "custom-software-development-sub", description: "Tailored solutions built from scratch to meet unique business needs." },
      { title: "Software for Enterprises", slug: "enterprise-software-development", description: "Developing extensive software systems designed for managing operations, administrative tasks, and data processing within large organizations." },
      { title: "SaaS (Software as a Service) Creation", slug: "saas-product-development", description: "Building cloud-hosted platforms that can serve multiple clients simultaneously, typically offered on a subscription basis." },
      { title: "ERP & CRM Solutions", slug: "erp-crm-solutions", description: "Providing internal software systems for managing enterprise resources and customer interactions." },
      { title: "Old Software Updates", slug: "legacy-software-modernization", description: "Revitalizing or updating outdated software systems by integrating contemporary technologies and practices." },
      { title: "Develop Desktop Programs", slug: "desktop-application-development", description: "Creating software applications compatible with Windows, macOS, or Linux operating systems." },
      { title: "API Creation & Connection", slug: "software-api-development-integration-sub", description: "Developing scalable APIs, including RESTful and GraphQL types, and integrating with external services." },
      { title: "Software Quality Control", slug: "software-testing-qa-sub", description: "Implementing both manual and automated testing processes to verify the functionality, performance, and security of software." },
      { title: "Software Care & Assistance", slug: "software-maintenance-support-sub", description: "Offering continuous service including system updates, issue resolution, and monitoring to maintain software performance." },
    ],
    description: "Delivering robust and scalable custom software solutions for diverse business challenges.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "custom software",
  },
  {
    title: "Artificial Intelligence Solutions",
    slug: "ai-development",
    icon: Brain,
    subServices: [
      { title: "AI Advisory Services", slug: "ai-consulting-sub", description: "Strategy, feasibility analysis, and roadmap creation for AI implementation." },
      { title: "Build AI Agents", slug: "ai-agent-development-sub", description: "Developing AI agents capable of independent decision-making and task execution, suitable for areas like customer service or operational automation." },
      { title: "Build AI Chatbots", slug: "ai-chatbot-development-sub", description: "Creating conversational AI bots, powered by technologies such as GPT, Dialogflow, or Rasa, for use on websites and applications." },
      { title: "Dynamic AI Systems", slug: "adaptive-ai-systems", description: "Constructing AI systems that evolve through learning and adjust their actions based on real-time environmental changes." },
      { title: "Natural Language Processing (NLP)", slug: "natural-language-processing", description: "Implementing techniques for analyzing and understanding human language, including categorizing text, gauging sentiment, summarizing content, and developing language models." },
      { title: "Computer Vision Technology", slug: "computer-vision-solutions", description: "Building systems capable of interpreting and analyzing visual input, encompassing features like recognizing objects, identifying faces, reading text via OCR, and performing visual data analysis." },
      { title: "Predictive Analytics", slug: "predictive-analytics", description: "Utilizing AI and statistical techniques to predict future trends and behaviors." },
      { title: "Voice AI & Voice Recognition", slug: "voice-ai-speech-recognition", description: "Developing AI systems that process and understand spoken language, including voice-controlled assistants and speech-to-text conversion tools." },
      { title: "Suggestive Systems", slug: "recommendation-systems", description: "Creating AI-driven systems that provide tailored suggestions for content, products, or services." },
      { title: "Deploy AI Models & MLOps", slug: "ai-model-deployment-mlops", description: "Managing the deployment of AI models and developing scalable AI workflows using platforms like TensorFlow Serving or SageMaker." },
    ],
    description: "Leveraging artificial intelligence and machine learning to build intelligent systems.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "artificial intelligence",
  },
  {
    title: "Blockchain Solutions",
    slug: "blockchain-development",
    icon: GitMerge,
    subServices: [
      { title: "Initial Coin Offering Services", slug: "ico-development-sub", description: "Launch support for Initial Coin Offerings, including smart contracts and whitepapers." },
      { title: "Create Smart Contracts", slug: "smart-contract-development-sub", description: "Crafting self-executing contracts on platforms such as Ethereum, BSC, or Polygon for applications like DeFi, NFTs, and DAOs." },
      { title: "Cryptocurrency Wallet Creation", slug: "wallet-development-sub", description: "Developing highly secure cryptocurrency wallets capable of holding multiple currencies for both web and mobile use, supporting both custodial and non-custodial options." },
      { title: "NFT Creation", slug: "nft-development-sub", description: "Providing comprehensive services for creating NFT marketplaces and tokens, including standards like ERC-721 and ERC-1155." },
      { title: "Build DeFi Platforms", slug: "defi-development-sub", description: "Constructing decentralized finance platforms that facilitate activities such as lending, staking, yield farming, and cryptocurrency exchanges." },
      { title: "Digital Asset Tokenization", slug: "asset-tokenization-sub", description: "Transforming tangible and digital assets, such as gold or company equity, into tradable tokens on the blockchain." },
      { title: "Tokenize Real Estate", slug: "real-estate-tokenization-sub", description: "Implementing systems that allow for partial ownership of property through smart contracts, creating new avenues for real estate investment." },
      { title: "Blockchain Advisory", slug: "blockchain-consulting", description: "Use-case evaluation, platform selection, compliance strategy, and architecture." },
      { title: "Private & Alliance Blockchain", slug: "private-consortium-blockchain", description: "Establishing restricted blockchain networks designed for corporate use, utilizing technologies like Hyperledger or Quorum." },
      { title: "Build dApps", slug: "dapp-development", description: "Decentralized application design with Web3 integrations and wallet connectivity." },
    ],
    description: "Exploring decentralized solutions with our expert blockchain development services.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "blockchain technology",
  },
   {
    title: "Cloud & DevOps Services",
    slug: "cloud-devops-services",
    description: "Streamline your development lifecycle and scale your infrastructure with our robust Cloud and DevOps solutions.",
    icon: Cloud,
    subServices: [
       { title: "Migrate to Cloud", slug: "cloud-migration", description: "Effortlessly transferring your applications and data to major cloud providers including AWS, Azure, and Google Cloud Platform." },
       { title: "Automated Infrastructure (IaC)", slug: "infrastructure-as-code", description: "Automating the setup and administration of IT infrastructure through code, using platforms such as Terraform and CloudFormation." },
       { title: "CI/CD Setup", slug: "ci-cd-pipelines", description: "Establishing systems for continuous integration and continuous delivery to enable quicker and more dependable software deployments." },
       { title: "Container and Orchestration Services", slug: "containerization-orchestration", description: "Implementing solutions like Docker and Kubernetes to create, deploy, and oversee applications packaged in containers." },
       { title: "System Monitoring & Logging", slug: "monitoring-logging", description: "Deploying detailed monitoring and logging systems to quickly detect and resolve potential issues." },
       { title: "Cloud Cost Optimization", slug: "cloud-cost-optimization", description: "Reviewing and refining your expenditure on cloud services to enhance efficiency without negatively impacting performance." }
    ],
    image: "https://placehold.co/600x400.png",
    dataAiHint: "cloud devops",
  },
  {
    title: "Tech Consultancy",
    slug: "tech-consultancy",
    description: "Expert guidance to navigate complex technology challenges and strategize for digital transformation.",
    icon: Users,
    subServices: [
      { title: "Digital Strategy Development", slug: "digital-transformation-strategy", description: "Crafting comprehensive strategies to seamlessly incorporate digital technologies throughout your entire business operation." },
      { title: "Technology Stack Advisory", slug: "technology-stack-advisory", description: "Offering professional recommendations for choosing the most suitable set of technologies to align with your project and business objectives." },
      { title: "IT Architecture Planning", slug: "it-architecture-planning", description: "Creating robust and scalable IT infrastructure blueprints designed to facilitate your business's expansion and adaptation." },
      { title: "Cybersecurity Consulting", slug: "cybersecurity-consulting", description: "Strengthening your security stance with expert evaluations, strategy formulation, and guidance on regulatory adherence." },
      { title: "Data Strategy & Reporting", slug: "data-strategy-analytics", description: "Utilizing data as a key strategic advantage through our services in data management, analysis, and business intelligence reporting." },
      { title: "Agile & DevOps Transition", slug: "agile-devops-transformation", description: "Facilitating the adoption of agile methods and DevOps approaches to boost efficiency, enhance teamwork, and accelerate product delivery." }
    ],
    image: "https://placehold.co/600x400.png",
    dataAiHint: "tech consultation",
  },
];


export const ALL_SERVICES_FLAT: ServiceMenuItem[] = [
  {
    title: "UI/UX Creation",
    slug: "ui-ux-design",
    icon: Palette,
    subServices: [],
    description: "Intuitive and visually appealing user interfaces that provide exceptional user experiences.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "ui ux design",
  },
  {
    title: "Product Planning",
    slug: "product-roadmap",
    icon: BarChartBig,
    subServices: [],
    description: "Strategic planning and roadmap development to guide your product's journey from concept to market success.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "product map",
  },
  {
    title: "Android App Building",
    slug: "android-app-development",
    icon: Smartphone,
    subServices: [],
    description: "Native Android applications built for performance and a seamless user experience on a wide range of devices.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "android apps",
  },
  {
    title: "iOS App Building",
    slug: "ios-app-development",
    icon: Smartphone,
    subServices: [],
    description: "Elegant and powerful iOS applications designed to meet Apple's high standards and delight users.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "ios apps",
  },
  {
    title: "Build Cross-Platform Apps",
    slug: "cross-platform-app-development",
    icon: Smartphone,
    subServices: [],
    description: "Efficiently build and deploy applications across multiple platforms (iOS, Android, Web) from a single codebase.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "cross platform apps",
  },
  {
    title: "Website Development",
    slug: "website-development",
    icon: Code,
    subServices: [],
    description: "Beautiful, responsive, and high-performing websites that serve as the digital face of your brand.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "build websites",
  },
  {
    title: "Web App Development",
    slug: "web-app-development",
    icon: DatabaseZap,
    subServices: [],
    description: "Complex and scalable web applications with rich interactivity and robust backend systems.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "web apps",
  },
  {
    title: "AI Consulting",
    slug: "ai-consulting",
    icon: MessageCircle,
    subServices: [],
    description: "Expert guidance to help you identify and implement AI solutions that drive business value and innovation.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "ai consulting",
  },
  {
    title: "AI Agent Development",
    slug: "ai-agent-development",
    icon: Bot,
    subServices: [],
    description: "Development of intelligent AI agents capable of autonomous decision-making and task execution.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "ai agents",
  },
  {
    title: "Adaptive AI Development",
    slug: "adaptive-ai-development",
    icon: Brain,
    subServices: [],
    description: "AI systems that learn and adapt over time, continuously improving performance and responsiveness.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "adaptive ai",
  },
  {
    title: "AI Chatbot Development",
    slug: "ai-chatbot-development",
    icon: MessageCircle,
    subServices: [],
    description: "Sophisticated AI-powered chatbots for customer service, engagement, and process automation.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "ai chatbots",
  },
  {
    title: "Custom Software Development",
    slug: "custom-software-development",
    icon: PenTool,
    subServices: [],
    description: "Bespoke software solutions meticulously crafted to meet your unique business requirements and objectives.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "custom software development",
  },
  {
    title: "Enterprise Software Development",
    slug: "enterprise-software-development",
    icon: Building2,
    subServices: [],
    description: "Robust and scalable software solutions designed for large organizations to optimize operations and drive growth.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "enterprise software",
  },
  {
    title: "ICO Development",
    slug: "ico-development",
    icon: Gem,
    subServices: [],
    description: "End-to-end Initial Coin Offering development services, from token creation to launch.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "ico development",
  },
  {
    title: "Wallet Development",
    slug: "wallet-development",
    icon: ShieldCheck,
    subServices: [],
    description: "Secure and user-friendly cryptocurrency wallet development for various blockchain platforms.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "wallet development",
  },
  {
    title: "Smart Contract Development",
    slug: "smart-contract-development",
    icon: FileCode,
    subServices: [],
    description: "Development of self-executing smart contracts for automating agreements and processes on the blockchain.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "smart contract development",
  },
  {
    title: "NFT Development",
    slug: "nft-development",
    icon: Gem,
    subServices: [],
    description: "Creation of Non-Fungible Tokens (NFTs) and marketplaces for digital collectibles and assets.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "nft development",
  },
  {
    title: "DeFi Development",
    slug: "defi-development",
    icon: GitBranch,
    subServices: [],
    description: "Building decentralized finance (DeFi) applications for lending, borrowing, trading, and more.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "defi development",
  },
  {
    title: "Asset Tokenization",
    slug: "asset-tokenization",
    icon: Layers,
    subServices: [],
    description: "Transforming real-world assets into digital tokens on the blockchain for increased liquidity and accessibility.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "asset tokenization",
  },
  {
    title: "Real Estate Tokenization",
    slug: "real-estate-tokenization",
    icon: Building2,
    subServices: [],
    description: "Tokenizing real estate assets to enable fractional ownership and new investment opportunities.",
    image: "https://placehold.co/600x400.png",
    dataAiHint: "real estate tokenization",
  },
];


export const PRODUCTS_DATA: Product[] = [
  {
    id: "1",
    name: "AI Chatbot Pro",
    description: "An intelligent chatbot leveraging NLP to enhance customer interactions.",
    stack: "Python, TensorFlow, React",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "ai chatbot",
    demoUrl: "#",
  },
  {
    id: "2",
    name: "Analytics Master",
    description: "AI-driven platform for deep data analysis and actionable business insights.",
    stack: "Scala, Spark, Next.js",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "data analytics",
    demoUrl: "#",
  },
  {
    id: "3",
    name: "AutoML Suite",
    description: "Automate your machine learning model building and deployment pipelines.",
    stack: "Python, Kubernetes, Flask",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "machine learning",
    demoUrl: "#",
  },
  {
    id: "4",
    name: "ContentGen GPT",
    description: "GPT-powered tool for generating high-quality marketing and sales content.",
    stack: "Node.js, OpenAI API, Vue.js",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "gpt content",
    demoUrl: "#",
  },
];

export const TIMELINE_EVENTS: TimelineEvent[] = [
  { year: "2018", title: "Founded", description: "Cubic Dot was founded with a vision to blend coffee, code, and creativity." },
  { year: "2019", title: "First AI Product Launch", description: "Launched our pioneering AI-driven analytics platform under the name Cubic Dot." },
  { year: "2020", title: "Team Expansion", description: "Grew our team to 20+ passionate innovators and developers." },
  { year: "2021", title: "New Office", description: "Moved into a new, state-of-the-art office space designed for collaboration." },
  { year: "2023", title: "Awarded Top AI Solutions Provider", description: "Recognized for excellence in AI and software development." },
];

export const BLOG_CATEGORIES: BlogCategory[] = [
  { id: "all", name: "All" },
  { id: "ai-ml", name: "AI/ML" },
  { id: "software-development", name: "Software Development" },
  { id: "ui-ux", name: "UI/UX" },
  { id: "devops", name: "DevOps" },
  { id: "company-news", name: "Company News" },
  { id: "blockchain", name: "Blockchain"},
  { id: "case-studies", name: "Case Studies"},
  { id: "tutorials", name: "Tutorials"},
];

export const BLOG_POSTS_DATA: BlogPost[] = [
  {
    id: "1",
    title: "The Future of AI in Business",
    slug: "future-of-ai-in-business",
    date: "2024-07-15",
    excerpt: "Discover how AI is reshaping industries and what it means for your business.",
    category: "ai-ml",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "artificial intelligence",
    content: "Full blog post content about the future of AI in business...",
    tags: ["AI", "Machine Learning", "Business"],
  },
  {
    id: "2",
    title: "Modern Software Development Practices",
    slug: "modern-software-development",
    date: "2024-07-10",
    excerpt: "An overview of the latest trends and best practices in software development.",
    category: "software-development",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "software development",
    content: "Full blog post content about modern software development practices...",
    tags: ["Agile", "DevOps", "Microservices"],
  },
  {
    id: "3",
    title: "Crafting Delightful User Experiences",
    slug: "crafting-delightful-ux",
    date: "2024-07-05",
    excerpt: "Tips and tricks for designing user interfaces that users love.",
    category: "ui-ux",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "ui design",
    content: "Full blog post content about crafting delightful user experiences...",
    tags: ["UX", "UI Design", "User Research"],
  },
  {
    id: "4",
    title: "Cubic Dot's Journey in AI",
    slug: "codecafe-lab-ai-journey",
    date: "2024-06-28",
    excerpt: "A look back at our milestones and innovations in the AI space.",
    category: "company-news",
    imageUrl: "https://placehold.co/600x400.png", 
    dataAiHint: "company journey",
    content: "Full blog post content about Cubic Dot's journey in AI...",
    tags: ["Cubic Dot", "AI Innovation", "Company Story"],
  },
  {
    id: "5",
    title: "Deep Dive into DeFi Development",
    slug: "deep-dive-defi-development",
    date: "2024-08-01",
    excerpt: "Exploring the core concepts and challenges of building Decentralized Finance applications.",
    category: "blockchain",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "defi blockchain",
    content: "Full blog post content about DeFi development...",
    tags: ["DeFi", "Blockchain", "Smart Contracts", "Ethereum"],
  },
  {
    id: "6",
    title: "Case Study: AI-Powered Logistics Optimization",
    slug: "case-study-ai-logistics-codecafe-lab",
    date: "2024-08-05",
    excerpt: "How Cubic Dot helped a major logistics firm reduce costs and improve efficiency using AI.",
    category: "case-studies",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "logistics ai",
    content: "Detailed case study on AI in logistics...",
    tags: ["AI", "Case Study", "Logistics", "Optimization", "Machine Learning"],
  },
  {
    id: "7",
    title: "Getting Started with Next.js: A Beginner's Tutorial",
    slug: "nextjs-beginners-tutorial",
    date: "2024-08-10",
    excerpt: "A step-by-step guide to building your first web application with Next.js.",
    category: "tutorials",
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "nextjs tutorial",
    content: "Comprehensive tutorial on Next.js for beginners...",
    tags: ["Next.js", "React", "Web Development", "Tutorial", "JavaScript"],
  },
];

export const FEATURED_VIDEOS_DATA: FeaturedVideo[] = [
  {
    id: 'video1',
    title: 'Intro to Our AI Platform',
    thumbnailUrl: '/video1s.png',
    videoSrc: '/video1.mp4',
    dataAiHint: 'ai platform demo',
    duration: '0:45',
  },
  {
    id: 'video2',
    title: 'Web Dev Best Practices',
    thumbnailUrl: '/video2s.png',
    videoSrc: '/video2.mp4',
    dataAiHint: 'coding tutorial screen',
    duration: '1:10',
  },
  {
    id: 'video3',
    title: 'A Day at Cubic Dot',
    thumbnailUrl: '/video3s.png',
    videoSrc: '/video3.mp4',
    dataAiHint: 'office team working',
    duration: '0:55',
  },
];


export const TECH_STACK_DATA: TechStackItem[] = [
  { name: "Next.js", icon: Package },
  { name: "React", icon: Package },
  { name: "TypeScript", icon: FileCode },
  { name: "Node.js", icon: Server },
  { name: "Python", icon: FileCode },
  { name: "AI / ML", icon: Brain },
  { name: "Genkit", icon: Settings2 },
  { name: "Tailwind CSS", icon: Palette },
  { name: "Firebase", icon: Cloud },
  { name: "Google Cloud", icon: Cloud },
  { name: "AWS", icon: Cloud },
  { name: "Docker", icon: Container },
  { name: "Kubernetes", icon: Share },
  { name: "PostgreSQL", icon: Database },
  { name: "MongoDB", icon: DatabaseZap },
  { name: "Git", icon: GitMerge },
  { name: "Figma", icon: PenTool },
  { name: "Android", icon: Smartphone },
  { name: "iOS", icon: Smartphone },
  { name: "Java", icon: FileCode },
  { name: "Kotlin", icon: FileCode },
  { name: "Swift", icon: FileCode },
  { name: "TensorFlow", icon: Cpu },
  { name: "PyTorch", icon: Cpu },
  { name: "HTML5", icon: CodeXml },
  { name: "CSS3", icon: Palette },
  { name: "JavaScript", icon: FileCode },
  { name: "REST APIs", icon: Cable },
  { name: "GraphQL", icon: FileJson },
  { name: "DevOps", icon: TerminalSquare },
  { name: "CI/CD", icon: ServerCog },
  { name: "Cybersecurity", icon: Shield },
  { name: "WebSockets", icon: Network },
  { name: "Microservices", icon: LayoutGrid },
  { name: "Headless CMS", icon: AppWindow },
];

export const TESTIMONIALS_DATA: Testimonial[] = [
  {
    id: "1",
    name: "Sarah Miller",
    role: "CEO, Innovatech Solutions",
    company: "Innovatech Solutions", 
    quote: "Cubic Dot transformed our vision into a reality with their exceptional AI expertise. Their team is not only skilled but also incredibly responsive and collaborative.",
    avatarUrl: "https://placehold.co/60x60.png",
    dataAiHint: "woman portrait",
    rating: 5,
  },
  {
    id: "2",
    name: "John Davis", 
    role: "CTO, QuantumLeap AI",
    company: "QuantumLeap AI",
    quote: "Working with Cubic Dot was a game-changer. Their deep understanding of complex algorithms and commitment to quality is unmatched.",
    avatarUrl: "https://placehold.co/60x60.png",
    dataAiHint: "man portrait",
    rating: 5,
  },
  {
    id: "3",
    name: "Emily Carter",
    role: "Product Manager, NextGen Apps",
    company: "NextGen Apps",
    quote: "The mobile app developed by Cubic Dot exceeded all our expectations in terms of design, functionality, and performance. Highly recommended!",
    avatarUrl: "https://placehold.co/60x60.png",
    dataAiHint: "woman avatar",
    rating: 4,
  },
  {
    id: "4",
    name: "Michael Brown", 
    role: "Founder, SparkUp Ventures",
    company: "SparkUp Ventures",
    quote: "As a startup, we needed a tech partner who was agile and innovative. Cubic Dot delivered on all fronts, helping us launch successfully.",
    avatarUrl: "https://placehold.co/60x60.png",
    dataAiHint: "man avatar",
    rating: 5,
  },
  {
    id: "5",
    name: "Jessica Williams", 
    role: "Head of Digital, ConnectFlow",
    company: "ConnectFlow Dynamics", 
    quote: "Their team's dedication and problem-solving skills are top-notch. Cubic Dot is our go-to for any complex software development needs.",
    avatarUrl: "https://placehold.co/60x60.png",
    dataAiHint: "woman professional",
    rating: 4,
  }
];
