
import type { NavItem, ServiceMenuItem, Product, TimelineEvent, BlogPost, BlogCategory, ProductSubMenuItem, TechStackItem, Testimonial, InstagramReel, OpenPosition } from '@/types';
import {
  Code, Smartphone, Brain, Cloud, Palette, Users, Bot, HomeIcon, Layers, Building2, FileText,
  Lightbulb, MessageCircle, ShieldCheck, PenTool, Server, Cpu, Gem, GitBranch, DatabaseZap, BarChartBig,
  Info, Briefcase, Mail, Globe, GitMerge, LayoutGrid, Puzzle, TrendingUp, Settings, DollarSign, Star, Link as LinkIcon,
  Clock, Car, QrCode, Package, Home, School, ChefHat, MessageSquare as MessageSquareIcon, Wrench, Truck, MonitorSmartphone, BarChart3, CircleDollarSign, Users2, Award, Handshake, CalendarPlus,
  DownloadCloud, Newspaper, CalendarClock, HelpCircle, BookOpenText, MailPlus, BarChartHorizontalBig, PlayCircle, Container, Share, Database, Settings2, Network, ServerCog, Shield, AppWindow, CodeXml, Cable, FileJson, TerminalSquare, Github, Linkedin, Twitter, Facebook, Send, Instagram, FileCode
} from 'lucide-react';

export const SITE_NAME = "CodeCafe Lab";

export const NAV_LINKS: NavItem[] = [
  { href: "/", label: "Home", icon: HomeIcon },
  { href: "/ai", label: "AI", icon: Bot },
  { href: "/services", label: "Services", icon: Layers },
  { href: "/products", label: "Products", icon: Smartphone },
  { href: "/company", label: "Company", icon: Building2 },
  { href: "/blog", label: "Resources", icon: FileText },
];

export const COMPANY_SUB_LINKS: NavItem[] = [
  {
    href: "/company",
    label: "About CodeCafe Lab",
    icon: Info,
    description: "Company mission, vision, values, founding story, leadership team, and journey."
  },
  {
    href: "/pricing",
    label: "Pricing",
    icon: CircleDollarSign,
    description: "We have transparent pricing modules for individuals, Startups, Companies."
  },
  {
    href: "/consultancy",
    label: "Consultancy",
    icon: Briefcase,
    description: "We provide consultancy for recruitment also."
  },
  {
    href: "/contact",
    label: "Contact Us",
    icon: Mail,
    description: "Contact form, phone, email, office locations, Google Maps embed, and social links."
  },
  {
    href: "/career",
    label: "Career",
    icon: Briefcase,
    description: "Current job openings, work culture, benefits, hiring process, and intern programs."
  },
  {
    href: "#",
    label: "Our Team",
    icon: Users2,
    description: "Photos, bios, and roles of key team members (adds a human touch)."
  },
  {
    href: "#",
    label: "Why Choose Us",
    icon: Award,
    description: "Key differentiators, client success stories, testimonials, and USPs."
  },
  {
    href: "#",
    label: "Partners & Affiliations",
    icon: Handshake,
    description: "Tech alliances, certifications, and strategic partners."
  },
];

export const PRODUCT_SUB_LINKS: ProductSubMenuItem[] = [
  {
    label: "Trackzy",
    subtitle: "(CCL Time Tracker)",
    description: "Smart time tracking for productive teams.",
    href: "#",
    icon: Clock,
  },
  {
    label: "AutoCleanse",
    subtitle: "(Doorstep Car Cleaning Service)",
    description: "Doorstep car wash, zero hassle.",
    href: "#",
    icon: Car,
  },
  {
    label: "QConnect",
    subtitle: "(Scan & Connect)",
    description: "Scan the QR. Connect instantly.",
    href: "#",
    icon: QrCode,
  },
  {
    label: "SwiftDrop",
    subtitle: "(Parcel Delivery #1)",
    description: "Next-gen parcel delivery at your command.",
    href: "#",
    icon: Package,
  },
  {
    label: "Neighbory",
    subtitle: "(Society Management)",
    description: "Simplifying society and community living.",
    href: "#",
    icon: HomeIcon,
  },
  {
    label: "ClientNest",
    subtitle: "(CRM)",
    description: "CRM that grows with your business.",
    href: "#",
    icon: Briefcase,
  },
  {
    label: "EduFlow",
    subtitle: "(School Management)",
    description: "Everything your school needs, in one place.",
    href: "#",
    icon: School,
  },
  {
    label: "DineOS",
    subtitle: "(Restra)",
    description: "Modern software for modern restaurants.",
    href: "#",
    icon: ChefHat,
  },
  {
    label: "WizZap",
    subtitle: "(WhatsApp Automation)",
    description: "Automated WhatsApp messaging for smart outreach.",
    href: "#",
    icon: MessageSquareIcon,
  },
  {
    label: "TeamSage",
    subtitle: "(HRMS)",
    description: "Smart HRMS for growing teams.",
    href: "#",
    icon: Users,
  },
  {
    label: "Servion",
    subtitle: "(On-demand Service App)",
    description: "On-demand services, reimagined.",
    href: "#",
    icon: Wrench,
  },
  {
    label: "DropChain",
    subtitle: "(Parcel Delivery #2)",
    description: "Reliable parcel logistics powered by smart tech.",
    href: "#",
    icon: Package,
  },
  {
    label: "Fleetzy",
    subtitle: "(Fleet Management)",
    description: "Fleet tracking and logistics, simplified.",
    href: "#",
    icon: Truck,
  },
  {
    label: "InstaSite",
    subtitle: "(Miniweb)",
    description: "Launch stunning mini websites in minutes.",
    href: "#",
    icon: MonitorSmartphone,
  },
  {
    label: "XpressRoute",
    subtitle: "(Parcel Delivery #3)",
    description: "Speed up your delivery, the smart way.",
    href: "#",
    icon: Package,
  },
  {
    label: "Pulselytics",
    subtitle: "(Social Media Data Dashboard)",
    description: "Real-time analytics for your social presence.",
    href: "#",
    icon: BarChart3,
  },
];

export const RESOURCES_SUB_LINKS: NavItem[] = [
  {
    href: "/blog",
    label: "Blog",
    icon: FileText,
    description: "Articles on tech trends, case studies, coding tips, AI advancements, and startup advice.",
  },
  {
    href: "#",
    label: "Case Studies",
    icon: BarChartHorizontalBig, // Using this as PresentationChart is not standard Lucide
    description: "Real client success stories with challenges, solutions, results, and testimonials.",
  },
  {
    href: "#",
    label: "Whitepapers & Reports",
    icon: DownloadCloud,
    description: "Downloadable PDFs on industry insights, AI, blockchain, or software strategy.",
  },
  {
    href: "#",
    label: "News & Announcements",
    icon: Newspaper,
    description: "Product launches, event participation, partnerships, awards, or media mentions.",
  },
  {
    href: "#",
    label: "Webinars & Events", // Optional
    icon: CalendarClock,
    description: "Upcoming webinars, past recordings, tech meetups, or training events.",
  },
  {
    href: "#",
    label: "Help Center / FAQs", // Optional
    icon: HelpCircle,
    description: "Support articles, onboarding guides, and general help topics.",
  },
  {
    href: "#",
    label: "Tutorials & How-Tos", // Optional
    icon: BookOpenText,
    description: "Technical tutorials, integrations, and walkthroughs for developers and clients.",
  },
  {
    href: "#",
    label: "Newsletter Signup", // Optional
    icon: MailPlus,
    description: "A place to collect emails for a monthly newsletter on company updates and tech trends.",
  },
];


export const SERVICES_DATA: ServiceMenuItem[] = [
  {
    title: "Ideation & Design",
    slug: "ideation-design",
    icon: Lightbulb,
    subServices: [
      { title: "UI/UX Design", slug: "ui-ux-design", description: "Wireframes, prototypes, high-fidelity designs, and usability testing." },
      { title: "Product Roadmap", slug: "product-roadmap", description: "Planning MVP, scaling strategy, feature prioritization, and timelines." },
      { title: "Design Thinking Workshops", slug: "design-thinking-workshops", description: "Interactive sessions to identify user pain points and innovation opportunities." },
      { title: "User Research & Personas", slug: "user-research-personas", description: "Target audience analysis, interviews, persona creation, and behavior mapping." },
      { title: "Brand Identity Design", slug: "brand-identity-design", description: "Logo, color schemes, typography, and brand guidelines for digital presence." },
      { title: "Information Architecture", slug: "information-architecture", description: "Sitemap creation, navigation planning, and content hierarchy." },
      { title: "Prototyping & Wireframing", slug: "prototyping-wireframing", description: "Clickable prototypes and low-fidelity screens to validate ideas quickly." },
      { title: "Competitor Analysis", slug: "competitor-analysis", description: "Market research and UX/UI comparisons for competitive differentiation." },
    ],
    description: "Transforming concepts into engaging and user-centric digital experiences.",
    image: "https://placehold.co/600x400/ffc011/000000.png?text=Ideation+Design",
    dataAiHint: "design thinking",
  },
  {
    title: "Mobile App Development",
    slug: "mobile-app-development",
    icon: Smartphone,
    subServices: [
      { title: "Android App Development", slug: "android-app-development", description: "Native Android apps using Java/Kotlin for performance and scalability." },
      { title: "iOS App Development", slug: "ios-app-development", description: "Native iPhone/iPad apps built with Swift for Apple ecosystems." },
      { title: "Cross-Platform App Development", slug: "cross-platform-app-development", description: "Apps using React Native, Flutter, or Xamarin for both iOS and Android." },
      { title: "Progressive Web Apps (PWA)", slug: "progressive-web-apps", description: "Web apps with native-like experiences for mobile browsers." },
      { title: "Mobile App UI/UX Design", slug: "mobile-app-ui-ux-design-sub", description: "Custom user interface design and mobile-specific UX strategy." },
      { title: "App Testing & QA", slug: "mobile-app-testing-qa", description: "Functional, performance, and user testing for bug-free launches." },
      { title: "App Deployment & Launch", slug: "mobile-app-deployment-launch", description: "Publishing to Google Play Store & Apple App Store with compliance." },
      { title: "App Maintenance & Support", slug: "mobile-app-maintenance-support-sub", description: "Post-launch updates, monitoring, and feature improvements." },
    ],
    description: "Building high-performance, scalable mobile applications for iOS and Android.",
    image: "https://placehold.co/600x400/008d00/ffffff.png?text=Mobile+Apps",
    dataAiHint: "mobile development",
  },
  {
    title: "Web Development",
    slug: "web-development",
    icon: Globe,
    subServices: [
      { title: "Website Development", slug: "website-development", description: "Responsive business websites, portfolios, landing pages, and CMS sites." },
      { title: "Web App Development", slug: "web-app-development-sub", description: "Custom web applications for internal tools, SaaS, dashboards, and portals." },
      { title: "E-Commerce Development", slug: "e-commerce-development", description: "Online store setup with WooCommerce, Shopify, or custom-built solutions." },
      { title: "Frontend Development", slug: "frontend-development", description: "React, Next.js, Vue.js, and modern JavaScript frameworks." },
      { title: "Backend Development", slug: "backend-development", description: "Node.js, Laravel, Python/Django, and scalable API development." },
      { title: "CMS & Custom Admin Panels", slug: "cms-custom-admin-panels", description: "WordPress, Strapi, Headless CMSs, or fully custom admin interfaces." },
      { title: "API Integration & Development (Web)", slug: "web-api-integration-development", description: "RESTful APIs, GraphQL, and third-party API integrations." },
      { title: "Performance Optimization", slug: "web-performance-optimization", description: "Speed, SEO, accessibility, and Core Web Vitals improvements." },
      { title: "Web Hosting & Deployment", slug: "web-hosting-deployment", description: "Scalable hosting setup on AWS, Vercel, Netlify, DigitalOcean, etc." },
    ],
    description: "Crafting dynamic websites and powerful web applications tailored to your needs.",
    image: "https://placehold.co/600x400/1c1c1c/ffffff.png?text=Web+Development",
    dataAiHint: "web design",
  },
  {
    title: "Software Development",
    slug: "software-development",
    icon: Server,
    subServices: [
      { title: "Custom Software Development", slug: "custom-software-development-sub", description: "Tailored solutions built from scratch to meet unique business needs." },
      { title: "Enterprise Software Development", slug: "enterprise-software-development", description: "Large-scale software systems for operations, management, or data processing." },
      { title: "SaaS Product Development", slug: "saas-product-development", description: "Cloud-based, multi-tenant platforms for subscription-based services." },
      { title: "ERP & CRM Solutions", slug: "erp-crm-solutions", description: "Internal tools for enterprise resource planning and customer relationship management." },
      { title: "Legacy Software Modernization", slug: "legacy-software-modernization", description: "Rebuilding or upgrading outdated systems using modern technologies." },
      { title: "Desktop Application Development", slug: "desktop-application-development", description: "Software for Windows, macOS, or Linux platforms." },
      { title: "API Development & Integration (Software)", slug: "software-api-development-integration", description: "Scalable RESTful or GraphQL APIs and third-party service integrations." },
      { title: "Software Testing & QA", slug: "software-testing-qa-sub", description: "Manual and automated testing for functionality, performance, and security." },
      { title: "Software Maintenance & Support", slug: "software-maintenance-support-sub", description: "Ongoing upgrades, troubleshooting, and performance monitoring." },
    ],
    description: "Delivering robust and scalable custom software solutions for diverse business challenges.",
    image: "https://placehold.co/600x400/ffc011/000000.png?text=Software+Development",
    dataAiHint: "custom software",
  },
  {
    title: "AI Development",
    slug: "ai-development",
    icon: Brain,
    subServices: [
      { title: "AI Consulting", slug: "ai-consulting-sub", description: "Strategy, feasibility analysis, and roadmap creation for AI implementation." },
      { title: "AI Agent Development", slug: "ai-agent-development-sub", description: "Autonomous agents for customer support, operations, or task automation." },
      { title: "AI Chatbot Development", slug: "ai-chatbot-development-sub", description: "Conversational AI bots using GPT, Dialogflow, or Rasa for websites and apps." },
      { title: "Adaptive AI Systems", slug: "adaptive-ai-systems", description: "Self-learning and behavior-adjusting systems for real-time environments." },
      { title: "Natural Language Processing (NLP)", slug: "natural-language-processing", description: "Text classification, sentiment analysis, summarization, and language models." },
      { title: "Computer Vision Solutions", slug: "computer-vision-solutions", description: "Object detection, face recognition, OCR, and visual analytics." },
      { title: "Predictive Analytics", slug: "predictive-analytics", description: "Forecasting trends and behaviors using AI-based statistical models." },
      { title: "Voice AI & Speech Recognition", slug: "voice-ai-speech-recognition", description: "Voice-based assistants and speech-to-text systems." },
      { title: "Recommendation Systems", slug: "recommendation-systems", description: "Personalized content, product, or service suggestions using AI." },
      { title: "AI Model Deployment & MLOps", slug: "ai-model-deployment-mlops", description: "Scalable AI pipeline management with tools like TensorFlow Serving or SageMaker." },
    ],
    description: "Leveraging artificial intelligence and machine learning to build intelligent systems.",
    image: "https://placehold.co/600x400/008d00/ffffff.png?text=AI+Development",
    dataAiHint: "artificial intelligence",
  },
  {
    title: "Blockchain Development",
    slug: "blockchain-development",
    icon: GitMerge,
    subServices: [
      { title: "ICO Development", slug: "ico-development-sub", description: "Launch support for Initial Coin Offerings, including smart contracts and whitepapers." },
      { title: "Smart Contract Development", slug: "smart-contract-development-sub", description: "Ethereum, BSC, or Polygon-based contracts for DeFi, NFTs, DAOs, etc." },
      { title: "Wallet Development", slug: "wallet-development-sub", description: "Secure multi-currency crypto wallets for web and mobile (custodial/non-custodial)." },
      { title: "NFT Development", slug: "nft-development-sub", description: "End-to-end NFT marketplace and token creation services (ERC-721, ERC-1155)." },
      { title: "DeFi Development", slug: "defi-development-sub", description: "Decentralized finance platforms for lending, staking, yield farming, and exchanges." },
      { title: "Asset Tokenization", slug: "asset-tokenization-sub", description: "Convert physical/digital assets (e.g., gold, equity) into blockchain-based tokens." },
      { title: "Real Estate Tokenization", slug: "real-estate-tokenization-sub", description: "Fractional ownership models using smart contracts for property investment." },
      { title: "Blockchain Consulting", slug: "blockchain-consulting", description: "Use-case evaluation, platform selection, compliance strategy, and architecture." },
      { title: "Private & Consortium Blockchain", slug: "private-consortium-blockchain", description: "Permissioned blockchain networks for enterprises using Hyperledger or Quorum." },
      { title: "dApp Development", slug: "dapp-development", description: "Decentralized application design with Web3 integrations and wallet connectivity." },
    ],
    description: "Exploring decentralized solutions with our expert blockchain development services.",
    image: "https://placehold.co/600x400/1c1c1c/ffffff.png?text=Blockchain+Tech",
    dataAiHint: "blockchain technology",
  },
   {
    title: "Cloud & DevOps Services",
    slug: "cloud-devops-services",
    description: "Streamline your development lifecycle and scale your infrastructure with our robust Cloud and DevOps solutions.",
    icon: Cloud,
    subServices: [
       { title: "Cloud Migration", slug: "cloud-migration", description: "Seamlessly move your applications and data to leading cloud platforms like AWS, Azure, or GCP." },
       { title: "Infrastructure as Code (IaC)", slug: "infrastructure-as-code", description: "Automate infrastructure provisioning and management using tools like Terraform and CloudFormation." },
       { title: "CI/CD Pipelines", slug: "ci-cd-pipelines", description: "Implement continuous integration and delivery pipelines for faster, reliable software releases." },
       { title: "Containerization & Orchestration", slug: "containerization-orchestration", description: "Utilize Docker and Kubernetes to build, deploy, and manage containerized applications." },
       { title: "Monitoring & Logging", slug: "monitoring-logging", description: "Set up comprehensive monitoring and logging solutions for proactive issue detection and resolution." },
       { title: "Cloud Cost Optimization", slug: "cloud-cost-optimization", description: "Analyze and optimize your cloud spending to ensure cost-efficiency without compromising performance." }
    ],
    image: "https://placehold.co/600x400/ffc011/000000.png?text=Cloud+DevOps",
    dataAiHint: "cloud devops",
  },
  {
    title: "Tech Consultancy",
    slug: "tech-consultancy",
    description: "Expert guidance to navigate complex technology challenges and strategize for digital transformation.",
    icon: Users,
    subServices: [
      { title: "Digital Transformation Strategy", slug: "digital-transformation-strategy", description: "Develop comprehensive strategies to integrate digital technology into all areas of your business." },
      { title: "Technology Stack Advisory", slug: "technology-stack-advisory", description: "Receive expert advice on selecting the optimal technology stack for your projects and business goals." },
      { title: "IT Architecture Planning", slug: "it-architecture-planning", description: "Design scalable and robust IT architectures that support your business's growth and evolution." },
      { title: "Cybersecurity Consulting", slug: "cybersecurity-consulting", description: "Enhance your security posture with expert assessments, strategy development, and compliance guidance." },
      { title: "Data Strategy & Analytics", slug: "data-strategy-analytics", description: "Leverage data as a strategic asset with our services in data governance, analytics, and BI." },
      { title: "Agile & DevOps Transformation", slug: "agile-devops-transformation", description: "Adopt agile methodologies and DevOps practices to improve efficiency, collaboration, and speed to market." }
    ],
    image: "https://placehold.co/600x400/008d00/ffffff.png?text=Tech+Consultancy",
    dataAiHint: "tech consultation",
  },
];


export const ALL_SERVICES_FLAT: ServiceMenuItem[] = [
  {
    title: "UI/UX Design",
    slug: "ui-ux-design",
    icon: Palette,
    subServices: [],
    description: "Intuitive and visually appealing user interfaces that provide exceptional user experiences.",
    image: "https://placehold.co/600x400/008d00/ffffff.png?text=UI+UX+Design",
    dataAiHint: "ui ux",
  },
  {
    title: "Product Roadmap",
    slug: "product-roadmap",
    icon: BarChartBig,
    subServices: [],
    description: "Strategic planning and roadmap development to guide your product's journey from concept to market success.",
    image: "https://placehold.co/600x400/ffc011/000000.png?text=Product+Roadmap",
    dataAiHint: "product strategy",
  },
  {
    title: "Android App Development",
    slug: "android-app-development",
    icon: Smartphone,
    subServices: [],
    description: "Native Android applications built for performance and a seamless user experience on a wide range of devices.",
    image: "https://placehold.co/600x400/008d00/ffffff.png?text=Android+App",
    dataAiHint: "android development",
  },
  {
    title: "iOS App Development",
    slug: "ios-app-development",
    icon: Smartphone,
    subServices: [],
    description: "Elegant and powerful iOS applications designed to meet Apple's high standards and delight users.",
    image: "https://placehold.co/600x400/ffc011/000000.png?text=iOS+App",
    dataAiHint: "ios development",
  },
  {
    title: "Cross-Platform App Development",
    slug: "cross-platform-app-development",
    icon: Smartphone,
    subServices: [],
    description: "Efficiently build and deploy applications across multiple platforms (iOS, Android, Web) from a single codebase.",
    image: "https://placehold.co/600x400/008d00/ffffff.png?text=Cross+Platform",
    dataAiHint: "cross platform",
  },
  {
    title: "Website Development",
    slug: "website-development",
    icon: Code,
    subServices: [],
    description: "Beautiful, responsive, and high-performing websites that serve as the digital face of your brand.",
    image: "https://placehold.co/600x400/ffc011/000000.png?text=Website+Dev",
    dataAiHint: "website creation",
  },
  {
    title: "Web App Development",
    slug: "web-app-development",
    icon: DatabaseZap,
    subServices: [],
    description: "Complex and scalable web applications with rich interactivity and robust backend systems.",
    image: "https://placehold.co/600x400/008d00/ffffff.png?text=Web+Application",
    dataAiHint: "web application",
  },
  {
    title: "AI Consulting",
    slug: "ai-consulting",
    icon: MessageCircle,
    subServices: [],
    description: "Expert guidance to help you identify and implement AI solutions that drive business value and innovation.",
    image: "https://placehold.co/600x400/ffc011/000000.png?text=AI+Consulting",
    dataAiHint: "ai strategy",
  },
  {
    title: "AI Agent Development",
    slug: "ai-agent-development",
    icon: Bot,
    subServices: [],
    description: "Development of intelligent AI agents capable of autonomous decision-making and task execution.",
    image: "https://placehold.co/600x400/008d00/ffffff.png?text=AI+Agents",
    dataAiHint: "intelligent agents",
  },
  {
    title: "Adaptive AI Development",
    slug: "adaptive-ai-development",
    icon: Brain,
    subServices: [],
    description: "AI systems that learn and adapt over time, continuously improving performance and responsiveness.",
    image: "https://placehold.co/600x400/ffc011/000000.png?text=Adaptive+AI",
    dataAiHint: "learning ai",
  },
  {
    title: "AI Chatbot Development",
    slug: "ai-chatbot-development",
    icon: MessageCircle,
    subServices: [],
    description: "Sophisticated AI-powered chatbots for customer service, engagement, and process automation.",
    image: "https://placehold.co/600x400/008d00/ffffff.png?text=AI+Chatbots",
    dataAiHint: "chatbot solutions",
  },
  {
    title: "Custom Software Development",
    slug: "custom-software-development",
    icon: PenTool,
    subServices: [],
    description: "Bespoke software solutions meticulously crafted to meet your unique business requirements and objectives.",
    image: "https://placehold.co/600x400/ffc011/000000.png?text=Custom+Software",
    dataAiHint: "bespoke software",
  },
  {
    title: "Enterprise Software Development",
    slug: "enterprise-software-development",
    icon: Building2,
    subServices: [],
    description: "Robust and scalable software solutions designed for large organizations to optimize operations and drive growth.",
    image: "https://placehold.co/600x400/008d00/ffffff.png?text=Enterprise+Software",
    dataAiHint: "enterprise solutions",
  },
  {
    title: "ICO Development",
    slug: "ico-development",
    icon: Gem,
    subServices: [],
    description: "End-to-end Initial Coin Offering development services, from token creation to launch.",
    image: "https://placehold.co/600x400/ffc011/000000.png?text=ICO+Dev",
    dataAiHint: "cryptocurrency ico",
  },
  {
    title: "Wallet Development",
    slug: "wallet-development",
    icon: ShieldCheck,
    subServices: [],
    description: "Secure and user-friendly cryptocurrency wallet development for various blockchain platforms.",
    image: "https://placehold.co/600x400/008d00/ffffff.png?text=Crypto+Wallet",
    dataAiHint: "crypto wallet",
  },
  {
    title: "Smart Contract Development",
    slug: "smart-contract-development",
    icon: FileText,
    subServices: [],
    description: "Development of self-executing smart contracts for automating agreements and processes on the blockchain.",
    image: "https://placehold.co/600x400/ffc011/000000.png?text=Smart+Contracts",
    dataAiHint: "blockchain contract",
  },
  {
    title: "NFT Development",
    slug: "nft-development",
    icon: Gem,
    subServices: [],
    description: "Creation of Non-Fungible Tokens (NFTs) and marketplaces for digital collectibles and assets.",
    image: "https://placehold.co/600x400/008d00/ffffff.png?text=NFT+Dev",
    dataAiHint: "nft marketplace",
  },
  {
    title: "DeFi Development",
    slug: "defi-development",
    icon: GitBranch,
    subServices: [],
    description: "Building decentralized finance (DeFi) applications for lending, borrowing, trading, and more.",
    image: "https://placehold.co/600x400/ffc011/000000.png?text=DeFi+Apps",
    dataAiHint: "decentralized finance",
  },
  {
    title: "Asset Tokenization",
    slug: "asset-tokenization",
    icon: Layers,
    subServices: [],
    description: "Transforming real-world assets into digital tokens on the blockchain for increased liquidity and accessibility.",
    image: "https://placehold.co/600x400/008d00/ffffff.png?text=Asset+Tokenization",
    dataAiHint: "digital assets",
  },
  {
    title: "Real Estate Tokenization",
    slug: "real-estate-tokenization",
    icon: Building2,
    subServices: [],
    description: "Tokenizing real estate assets to enable fractional ownership and new investment opportunities.",
    image: "https://placehold.co/600x400/ffc011/000000.png?text=Real+Estate+Tokens",
    dataAiHint: "property tokenization",
  },
];


export const PRODUCTS_DATA: Product[] = [
  {
    id: "1",
    name: "AI Chatbot Pro",
    description: "An intelligent chatbot leveraging NLP to enhance customer interactions.",
    stack: "Python, TensorFlow, React",
    imageUrl: "https://placehold.co/600x400/ffc011/1c1c1c.png?text=Chatbot+Pro",
    dataAiHint: "ai chatbot",
    demoUrl: "#",
  },
  {
    id: "2",
    name: "Analytics Master",
    description: "AI-driven platform for deep data analysis and actionable business insights.",
    stack: "Scala, Spark, Next.js",
    imageUrl: "https://placehold.co/600x400/008d00/ffffff.png?text=Analytics+Master",
    dataAiHint: "data analytics",
    demoUrl: "#",
  },
  {
    id: "3",
    name: "AutoML Suite",
    description: "Automate your machine learning model building and deployment pipelines.",
    stack: "Python, Kubernetes, Flask",
    imageUrl: "https://placehold.co/600x400/ffc011/1c1c1c.png?text=AutoML+Suite",
    dataAiHint: "machine learning",
    demoUrl: "#",
  },
  {
    id: "4",
    name: "ContentGen GPT",
    description: "GPT-powered tool for generating high-quality marketing and sales content.",
    stack: "Node.js, OpenAI API, Vue.js",
    imageUrl: "https://placehold.co/600x400/008d00/ffffff.png?text=ContentGen+GPT",
    dataAiHint: "gpt content",
    demoUrl: "#",
  },
];

export const TIMELINE_EVENTS: TimelineEvent[] = [
  { year: "2018", title: "Founded", description: "CodeCafe Lab was founded with a vision to blend coffee, code, and creativity." },
  { year: "2019", title: "First AI Product Launch", description: "Launched our pioneering AI-driven analytics platform." },
  { year: "2020", title: "Team Expansion", description: "Grew our team to 20+ passionate innovators and developers." },
  { year: "2021", title: "New Office", description: "Moved into a new, state-of-the-art office space designed for collaboration." },
  { year: "2023", title: "Awarded Top AI Solutions Provider", description: "Recognized for excellence in AI and software development." },
];

export const BLOG_CATEGORIES: BlogCategory[] = [
  { id: "all", name: "All" },
  { id: "ai-ml", name: "AI/ML" },
  { id: "software-development", name: "Software Development" },
  { id: "ui-ux", name: "UI/UX" },
  { id: "devops", name: "DevOps" },
  { id: "company-news", name: "Company News" },
  { id: "blockchain", name: "Blockchain"},
  { id: "case-studies", name: "Case Studies"},
  { id: "tutorials", name: "Tutorials"},
];

export const BLOG_POSTS_DATA: BlogPost[] = [
  {
    id: "1",
    title: "The Future of AI in Business",
    slug: "future-of-ai-in-business",
    date: "2024-07-15",
    excerpt: "Discover how AI is reshaping industries and what it means for your business.",
    category: "ai-ml",
    imageUrl: "https://placehold.co/600x400/ffc011/1c1c1c.png?text=AI+Future",
    dataAiHint: "artificial intelligence",
    content: "Full blog post content about the future of AI in business...",
    tags: ["AI", "Machine Learning", "Business"],
  },
  {
    id: "2",
    title: "Modern Software Development Practices",
    slug: "modern-software-development",
    date: "2024-07-10",
    excerpt: "An overview of the latest trends and best practices in software development.",
    category: "software-development",
    imageUrl: "https://placehold.co/600x400/008d00/ffffff.png?text=Software+Dev",
    dataAiHint: "software development",
    content: "Full blog post content about modern software development practices...",
    tags: ["Agile", "DevOps", "Microservices"],
  },
  {
    id: "3",
    title: "Crafting Delightful User Experiences",
    slug: "crafting-delightful-ux",
    date: "2024-07-05",
    excerpt: "Tips and tricks for designing user interfaces that users love.",
    category: "ui-ux",
    imageUrl: "https://placehold.co/600x400/ffc011/1c1c1c.png?text=UX+Design",
    dataAiHint: "ui design",
    content: "Full blog post content about crafting delightful user experiences...",
    tags: ["UX", "UI Design", "User Research"],
  },
  {
    id: "4",
    title: "CodeCafe Lab's Journey in AI",
    slug: "codecafe-lab-ai-journey",
    date: "2024-06-28",
    excerpt: "A look back at our milestones and innovations in the AI space.",
    category: "company-news",
    imageUrl: "https://placehold.co/600x400/008d00/ffffff.png?text=Company+AI",
    dataAiHint: "company journey",
    content: "Full blog post content about CodeCafe Lab's journey in AI...",
    tags: ["CodeCafe Lab", "AI Innovation", "Company Story"],
  },
  {
    id: "5",
    title: "Deep Dive into DeFi Development",
    slug: "deep-dive-defi-development",
    date: "2024-08-01",
    excerpt: "Exploring the core concepts and challenges of building Decentralized Finance applications.",
    category: "blockchain",
    imageUrl: "https://placehold.co/600x400/ffc011/1c1c1c.png?text=DeFi+Deep+Dive",
    dataAiHint: "decentralized finance blockchain",
    content: "Full blog post content about DeFi development...",
    tags: ["DeFi", "Blockchain", "Smart Contracts", "Ethereum"],
  },
  {
    id: "6",
    title: "Case Study: AI-Powered Logistics Optimization",
    slug: "case-study-ai-logistics",
    date: "2024-08-05",
    excerpt: "How CodeCafe Lab helped a major logistics firm reduce costs and improve efficiency using AI.",
    category: "case-studies",
    imageUrl: "https://placehold.co/600x400/008d00/ffffff.png?text=AI+Logistics+Case+Study",
    dataAiHint: "logistics optimization ai",
    content: "Detailed case study on AI in logistics...",
    tags: ["AI", "Case Study", "Logistics", "Optimization", "Machine Learning"],
  },
  {
    id: "7",
    title: "Getting Started with Next.js: A Beginner's Tutorial",
    slug: "nextjs-beginners-tutorial",
    date: "2024-08-10",
    excerpt: "A step-by-step guide to building your first web application with Next.js.",
    category: "tutorials",
    imageUrl: "https://placehold.co/600x400/ffc011/1c1c1c.png?text=NextJS+Tutorial",
    dataAiHint: "nextjs tutorial web",
    content: "Comprehensive tutorial on Next.js for beginners...",
    tags: ["Next.js", "React", "Web Development", "Tutorial", "JavaScript"],
  },
];


export const INSTAGRAM_REELS_DATA: InstagramReel[] = [
  {
    id: 'reel1',
    title: 'Meta AI Showcase Reel',
    thumbnailUrl: 'https://placehold.co/270x480.png?text=Meta+AI+Reel', // Placeholder
    instagramUrl: 'https://www.instagram.com/reel/DJZ0qPoSIUt/',
    dataAiHint: 'meta ai reel',
    duration: '0:58', // Placeholder
  },
  {
    id: 'reel2',
    title: 'Behind the Scenes at CodeCafe',
    thumbnailUrl: 'https://placehold.co/270x480.png?text=CodeCafe+BTS', // Placeholder
    instagramUrl: 'https://www.instagram.com/reel/DJ2PNKOBwNe/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    dataAiHint: 'office life',
    duration: '0:55', // Placeholder
  },
  {
    id: 'reel3',
    title: 'AI Project Teaser',
    thumbnailUrl: 'https://placehold.co/270x480.png?text=AI+Project', // Placeholder
    instagramUrl: 'https://www.instagram.com/reel/C0JZc85yggS/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    dataAiHint: 'ai project',
    duration: '0:30', // Placeholder
  },
];


export const TECH_STACK_DATA: TechStackItem[] = [
  { name: "Next.js", icon: Package },
  { name: "React", icon: Package },
  { name: "TypeScript", icon: FileCode },
  { name: "Node.js", icon: Server },
  { name: "Python", icon: FileCode },
  { name: "AI / ML", icon: Brain },
  { name: "Genkit", icon: Settings2 },
  { name: "Tailwind CSS", icon: Palette },
  { name: "Firebase", icon: Cloud },
  { name: "Google Cloud", icon: Cloud },
  { name: "AWS", icon: Cloud },
  { name: "Docker", icon: Container },
  { name: "Kubernetes", icon: Share }, // 13th item
  { name: "PostgreSQL", icon: Database },
  { name: "MongoDB", icon: DatabaseZap },
  { name: "Git", icon: GitMerge },
  { name: "Figma", icon: PenTool },
  { name: "Android", icon: Smartphone },
  { name: "iOS", icon: Smartphone },
  { name: "Java", icon: FileCode },
  { name: "Kotlin", icon: FileCode },
  { name: "Swift", icon: FileCode },
  { name: "TensorFlow", icon: Cpu },
  { name: "PyTorch", icon: Cpu }, // 24th item
  { name: "HTML5", icon: CodeXml },
  { name: "CSS3", icon: Palette },
  { name: "JavaScript", icon: FileCode },
  { name: "REST APIs", icon: Cable },
  { name: "GraphQL", icon: FileJson },
  { name: "DevOps", icon: TerminalSquare },
  { name: "CI/CD", icon: ServerCog },
  { name: "Cybersecurity", icon: Shield },
  { name: "WebSockets", icon: Network },
  { name: "Microservices", icon: LayoutGrid },
  { name: "Headless CMS", icon: AppWindow }, // 35th item
];

export const TESTIMONIALS_DATA: Testimonial[] = [
  {
    id: "1",
    name: "Sarah Miller",
    role: "CEO, Innovatech Solutions",
    company: "Innovatech Solutions",
    quote: "CodeCafe Lab transformed our vision into a reality with their exceptional AI expertise. Their team is not only skilled but also incredibly responsive and collaborative.",
    avatarUrl: "https://placehold.co/60x60.png",
    dataAiHint: "woman portrait",
    rating: 5,
  },
  {
    id: "2",
    name: "John Davis",
    role: "CTO, QuantumLeap AI",
    company: "QuantumLeap AI",
    quote: "Working with CodeCafe Lab was a game-changer. Their deep understanding of complex algorithms and commitment to quality is unmatched.",
    avatarUrl: "https://placehold.co/60x60.png",
    dataAiHint: "man portrait",
    rating: 5,
  },
  {
    id: "3",
    name: "Emily Carter",
    role: "Product Manager, NextGen Apps",
    company: "NextGen Apps",
    quote: "The mobile app developed by CodeCafe Lab exceeded all our expectations in terms of design, functionality, and performance. Highly recommended!",
    avatarUrl: "https://placehold.co/60x60.png",
    dataAiHint: "woman avatar",
    rating: 4,
  },
  {
    id: "4",
    name: "Michael Brown",
    role: "Founder, SparkUp Ventures",
    company: "SparkUp Ventures",
    quote: "As a startup, we needed a tech partner who was agile and innovative. CodeCafe Lab delivered on all fronts, helping us launch successfully.",
    avatarUrl: "https://placehold.co/60x60.png",
    dataAiHint: "man avatar",
    rating: 5,
  },
  {
    id: "5",
    name: "Jessica Williams",
    role: "Head of Digital Transformation, ConnectFlow Dynamics",
    company: "ConnectFlow Dynamics",
    quote: "Their team's dedication and problem-solving skills are top-notch. CodeCafe Lab is our go-to for any complex software development needs.",
    avatarUrl: "https://placehold.co/60x60.png",
    dataAiHint: "woman professional",
    rating: 4,
  }
];

// The HTML embed code provided by the user
// const specificReelEmbedHtml = `<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-permalink="https://www.instagram.com/reel/DJZ0qPoSIUt/?utm_source=ig_embed&amp;utm_campaign=loading" data-instgrm-version="14" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:540px; min-width:326px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:16px;"> <a href="https://www.instagram.com/reel/DJZ0qPoSIUt/?utm_source=ig_embed&amp;utm_campaign=loading" style=" background:#FFFFFF; line-height:0; padding:0 0; text-align:center; text-decoration:none; width:100%;" target="_blank"> <div style=" display: flex; flex-direction: row; align-items: center;"> <div style="background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 40px; margin-right: 14px; width: 40px;"></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 100px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 60px;"></div></div></div><div style="padding: 19% 0;"></div> <div style="display:block; height:50px; margin:0 auto 12px; width:50px;"><svg width="50px" height="50px" viewBox="0 0 60 60" version="1.1" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g transform="translate(-511.000000, -20.000000)" fill="#000000"><g><path d="M556.869,30.41 C554.814,30.41 553.148,32.076 553.148,34.131 C553.148,36.186 554.814,37.852 556.869,37.852 C558.924,37.852 560.59,36.186 560.59,34.131 C560.59,32.076 558.924,30.41 556.869,30.41 M541,60.657 C535.114,60.657 530.342,55.887 530.342,50 C530.342,44.114 535.114,39.342 541,39.342 C546.887,39.342 551.658,44.114 551.658,50 C551.658,55.887 546.887,60.657 541,60.657 M541,33.886 C532.1,33.886 524.886,41.1 524.886,50 C524.886,58.899 532.1,66.113 541,66.113 C549.9,66.113 557.115,58.899 557.115,50 C557.115,41.1 549.9,33.886 541,33.886 M565.378,62.101 C565.244,65.022 564.756,66.606 564.346,67.663 C563.803,69.06 563.154,70.057 562.106,71.106 C561.058,72.155 560.06,72.803 558.662,73.347 C557.607,73.757 556.021,74.244 553.102,74.378 C549.944,74.521 548.997,74.552 541,74.552 C533.003,74.552 532.056,74.521 528.898,74.378 C525.979,74.244 524.393,73.757 523.338,73.347 C521.94,72.803 520.942,72.155 519.894,71.106 C518.846,70.057 518.197,69.06 517.654,67.663 C517.244,66.606 516.755,65.022 516.623,62.101 C516.479,58.943 516.448,57.996 516.448,50 C516.448,42.003 516.479,41.056 516.623,37.899 C516.755,34.978 517.244,33.391 517.654,32.338 C518.197,30.938 518.846,29.942 519.894,28.894 C520.942,27.846 521.94,27.196 523.338,26.654 C524.393,26.244 525.979,25.756 528.898,25.623 C532.057,25.479 533.004,25.448 541,25.448 C548.997,25.448 549.943,25.479 553.102,25.623 C556.021,25.756 557.607,26.244 558.662,26.654 C560.06,27.196 561.058,27.846 562.106,28.894 C563.154,29.942 563.803,30.938 564.346,32.338 C564.756,33.391 565.244,34.978 565.378,37.899 C565.522,41.056 565.552,42.003 565.552,50 C565.552,57.996 565.522,58.943 565.378,62.101 M570.82,37.631 C570.674,34.438 570.167,32.258 569.425,30.349 C568.659,28.377 567.633,26.702 565.965,25.035 C564.297,23.368 562.623,22.342 560.652,21.575 C558.743,20.834 556.562,20.326 553.369,20.18 C550.169,20.033 549.148,20 541,20 C532.853,20 531.831,20.033 528.631,20.18 C525.438,20.326 523.257,20.834 521.349,21.575 C519.376,22.342 517.703,23.368 516.035,25.035 C514.368,26.702 513.342,28.377 512.574,30.349 C511.834,32.258 511.326,34.438 511.181,37.631 C511.035,40.831 511,41.851 511,50 C511,58.147 511.035,59.17 511.181,62.369 C511.326,65.562 511.834,67.743 512.574,69.651 C513.342,71.625 514.368,73.296 516.035,74.965 C517.703,76.634 519.376,77.658 521.349,78.425 C523.257,79.167 525.438,79.673 528.631,79.82 C531.831,79.965 532.853,80.001 541,80.001 C549.148,80.001 550.169,79.965 553.369,79.82 C556.562,79.673 558.743,79.167 560.652,78.425 C562.623,77.658 564.297,76.634 565.965,74.965 C567.633,73.296 568.659,71.625 569.425,69.651 C570.167,67.743 570.674,65.562 570.82,62.369 C570.966,59.17 571,58.147 571,50 C571,41.851 570.966,40.831 570.82,37.631"></path></g></g></g></svg></div><div style="padding-top: 8px;"> <div style=" color:#3897f0; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:550; line-height:18px;">View this post on Instagram</div></div><div style="padding: 12.5% 0;"></div> <div style="display: flex; flex-direction: row; margin-bottom: 14px; align-items: center;"><div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(0px) translateY(7px);"></div> <div style="background-color: #F4F4F4; height: 12.5px; transform: rotate(-45deg) translateX(3px) translateY(1px); width: 12.5px; flex-grow: 0; margin-right: 14px; margin-left: 2px;"></div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(9px) translateY(-18px);"></div></div><div style="margin-left: 8px;"> <div style=" background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 20px; width: 20px;"></div> <div style=" width: 0; height: 0; border-top: 2px solid transparent; border-left: 6px solid #f4f4f4; border-bottom: 2px solid transparent; transform: translateX(16px) translateY(-4px) rotate(30deg)"></div></div><div style="margin-left: auto;"> <div style=" width: 0px; border-top: 8px solid #F4F4F4; border-right: 8px solid transparent; transform: translateY(16px);"></div> <div style=" background-color: #F4F4F4; flex-grow: 0; height: 12px; width: 16px; transform: translateY(-4px);"></div> <div style=" width: 0; height: 0; border-top: 8px solid #F4F4F4; border-left: 8px solid transparent; transform: translateY(-4px) translateX(8px);"></div></div></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center; margin-bottom: 24px;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 224px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 144px;"></div></div></a><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://www.instagram.com/reel/DJZ0qPoSIUt/?utm_source=ig_embed&amp;utm_campaign=loading" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_blank">A post shared by Meta AI (@meta.ai)</a></p></div></blockquote>`;
// const specificReelId = 'DJZ0qPoSIUt'; // This is the ID from the embed code
